In [21]:
import pandas as pd
from io import StringIO
Data = '{"employee_name": ["James","Manoj Badshah"], "email":[ "james@gmail.com", "manoj@gmail.com"], "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}, {"title1":"Team Lead", "title2":"Sr. Developer"}], "salary": [1000, 2000]}'
df=pd.read_json(StringIO(Data))

In [22]:
print(Data)

{"employee_name": ["James","Manoj Badshah"], "email":[ "james@gmail.com", "manoj@gmail.com"], "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}, {"title1":"Team Lead", "title2":"Sr. Developer"}], "salary": [1000, 2000]}

In [23]:
context=df.to_json(orient='records', lines=True, index=False)
print(context)

{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"},"salary":1000}
{"employee_name":"Manoj Badshah","email":"manoj@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"},"salary":2000}

In [28]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None)
print(df.head(5))
print(df.describe())

   0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93

     13
0  1065
1  1050
2  1185
3  1480
4   735
               0           1           2           3           4           5   \
count  178.000000  178.000000  178.000000  178.000000  178.000000  178.000000
mean     1.938202   13.000618    2.336348    2.366517   19.494944   99.741573
std      0.775035    0.811827    1.117146    0.274344    3.339564   14.282484
min      1.000000   11.030000    0.740000    1.360000   10.600000   70.000000
25%      1.000000   12.362500    1.602500    2.210000   17.200000   88.000000
50%      2.000000   13.050000    1.865000    2.360000   19.500000   98.000000
75%      3.000000   13.677500    3.082500    2.557500   21.500000  107.000000
max      3.000000   14.830000    5.800000    3.230000   30.000000  162.000000

               6           7           8           9           10          11  \
count  178.000000  178.000000  178.000000  178.000000  178.000000  178.000000
mean     2.295112    2.029270    0.361854    1.590899    5.058090    0.957449
std      0.625851    0.998859    0.124453    0.572359    2.318286    0.228572
min      0.980000    0.340000    0.130000    0.410000    1.280000    0.480000
25%      1.742500    1.205000    0.270000    1.250000    3.220000    0.782500
50%      2.355000    2.135000    0.340000    1.555000    4.690000    0.965000
75%      2.800000    2.875000    0.437500    1.950000    6.200000    1.120000
max      3.880000    5.080000    0.660000    3.580000   13.000000    1.710000

               12           13
count  178.000000   178.000000
mean     2.611685   746.893258
std      0.709990   314.907474
min      1.270000   278.000000
25%      1.937500   500.500000
50%      2.780000   673.500000
75%      3.170000   985.000000
max      4.000000  1680.000000

In [29]:
df.to_csv("wine.csv", index=False)

In [31]:
timepass=pd.read_csv("wine.csv")

In [33]:
timepass.head(5)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [35]:
!pip install lxml

Collecting lxml
  Downloading lxml-5.3.1-cp310-cp310-win_amd64.whl.metadata (3.8 kB)
Downloading lxml-5.3.1-cp310-cp310-win_amd64.whl (3.8 MB)
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   -------- ------------------------------- 0.8/3.8 MB 8.5 MB/s eta 0:00:01
   ------------------------------ --------- 2.9/3.8 MB 16.8 MB/s eta 0:00:01
   ------------------------------ --------- 2.9/3.8 MB 16.8 MB/s eta 0:00:01
   --------------------------------- ------ 3.1/3.8 MB 4.9 MB/s eta 0:00:01
   -------------------------------------- - 3.7/3.8 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 3.3 MB/s eta 0:00:00
Installing collected packages: lxml
Successfully installed lxml-5.3.1

In [36]:
url="https://www.fdic.gov/bank-failures/failed-bank-list"
df=pd.read_html(url)
print(len(df))

1

In [44]:
df[0].head(5)

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
1,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,"First Bank & Trust Co., Duncan, OK","October 18, 2024",10547
2,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
3,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
4,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544